# Generated by Django 4.1.5 on 2023-01-17 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carddata',
            name='upload',
        ),
    ]
