# Generated by Django 4.1.5 on 2023-01-17 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapp', '0009_alter_carddata_company_alter_carddata_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carddata',
            name='upload',
            field=models.ImageField(blank=True, upload_to='uploads'),
        ),
    ]
