# Generated by Django 4.1.5 on 2023-01-19 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapp', '0011_alter_carddata_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carddata',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
