# Generated by Django 4.1.5 on 2023-01-20 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapp', '0012_alter_carddata_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carddata',
            name='phone',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
