# Generated by Django 4.1.5 on 2023-01-20 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapp', '0013_alter_carddata_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='carddata',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes'),
        ),
    ]
