# Generated by Django 4.1.5 on 2023-01-20 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardapp', '0017_remove_carddata_qr_code_carddata_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carddata',
            name='code',
        ),
    ]
