# Generated by Django 4.1.5 on 2023-02-28 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapp', '0023_alter_carddata_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carddata',
            name='middlename',
        ),
        migrations.AddField(
            model_name='carddata',
            name='alternatephone',
            field=models.CharField(max_length=11, null=True, unique=True),
        ),
    ]
