# Generated by Django 4.1.5 on 2023-03-29 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapp', '0026_remove_carddata_firstname_remove_carddata_lastname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carddata',
            name='alternatephone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='carddata',
            name='upload',
            field=models.ImageField(blank=True, null=True, upload_to='uploads'),
        ),
    ]
