# Generated by Django 4.1.5 on 2023-04-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapp', '0031_alter_carddata_alternatephone_alter_carddata_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carddata',
            name='alternatephone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
