# Generated by Django 4.1.5 on 2023-04-05 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapp', '0035_carddata_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carddata',
            name='user',
        ),
        migrations.AlterField(
            model_name='carddata',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
