# Generated by Django 4.1.5 on 2023-04-05 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapp', '0036_remove_carddata_user_alter_carddata_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='carddata',
            name='username',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
