name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
    - name: Start uWSGI
      run: |
       uwsgi --socket /run/uwsgi/mysite.sock --chdir /home/ubuntu/project_django/ --module project_django.wsgi --chmod-socket=666 --daemonize /dev/null 
    - name: Reboot system
      run: |
        sudo reboot 
    - name: Restart nginx
      run: |
        sudo systemctl start nginx
        sudo systemctl enable nginx
        sudo systemctl enable uwsgi
